### ISSUE TITLE
Errors in Console

### ISSUE THREAD

**Issue by amit177** [weeryan17/Discord-Groups#3]
After starting the server,
the plugin drops this error:

http://pastebin.com/g5StQwzN

**Comment by weeryan17** [comment]
Are you using a hosting site like mcprohosting?

**Comment by amit177** [comment]
No, Im using my computer

**Comment by weeryan17** [comment]
Ok by the looks of it your config isn't properly configured. you need to put your bot token in the config and you need to put the name of you main channel in the config. if you need help with that just tell me.

**Comment by amit177** [comment]
I changed the token to the right one, and in the main channel I wrote #general, thats on my server

**Comment by weeryan17** [comment]
Just do general. the # is just for organization it isn't actually in the name of the channel.

**Comment by amit177** [comment]
same error again

**Comment by weeryan17** [comment]
Do you have your bot properly joined to your server?

**Comment by amit177** [comment]
Do I need to authorize it alone? I thought the plugin will do it.. Let me try

**Comment by amit177** [comment]
Okay, It works now! Thanks 👍
