### ISSUE TITLE
Multiple problems, groups/IGN not syncing

### ISSUE THREAD

**Issue by Natedanp** [weeryan17/Discord-Groups#6]
Okay, well I ran into a few problems while setting the plugin up, first, the groups and in-game IGNs are not syncing. You didn't really explain how to making group syncing work in the plugin overview, but I went on a limb and created the same exact rank names on Discord as in-game, gave myself the ranks in-game and synced my accounts, but my ranks have yet to sync, nor did my IGN. And second, the messages when syncing accounts need to be properly setup, as the "A message has been sent to you in minecraft with the id you need to link discord and minecraft" message should have something telling the user what command to use to link the account, and the messages should be properly worded, something like what I did [here](http://pastebin.com/J5439Ewp) as they currently look very unprofessional for the plugin user. With the group and IGN syncing thing, am I doing something wrong? Bot is only on one server and ignsync is on, and the bot has full access to ranking people and stuff. Using PermissionsEX. Just noticed it is throwing errors in console, multiple times every few seconds. [This](http://hastebin.com/jodiwupuca.lua) is the error.

**Comment by weeryan17** [comment]
wow that's a lot of issues. I'm going to break this big issue up into multiple issues so it's easier for me to keep track of.

**Comment by weeryan17** [comment]
so i split this up into three issues so for now on look at isuue #7 #8 and #9

**Comment by weeryan17** [comment]
@Natedanp make sure to check out the other issues. i believe most of the bugs are fixed after i updated to discord4j version 2.7 but I'm not having a problem so i suggest you update and tell me what is still broken.
